/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.Controller;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author unifjbarreto
 */
public class painelPlaylistIndividual extends javax.swing.JPanel {

    private int id_playlist;
    private Controller controller;
    public painelPlaylistIndividual(Controller controller,int id) {
        this.controller = controller;
        this.id_playlist = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditarPlaylist = new javax.swing.JButton();
        txtNomePlaylist1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(10000, 47));

        btnEditarPlaylist.setText("Editar");
        btnEditarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPlaylistActionPerformed(evt);
            }
        });

        txtNomePlaylist1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtNomePlaylist1.setText("Nome Playlist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(txtNomePlaylist1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarPlaylist))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEditarPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(txtNomePlaylist1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPlaylistActionPerformed
        this.controller.abrirEditorPlaylist(id_playlist);
    }//GEN-LAST:event_btnEditarPlaylistActionPerformed

    public int getId_playlist() {
        return id_playlist;
    }

    public void setId_playlist(int id_playlist) {
        this.id_playlist = id_playlist;
    }

    public Controller getController() {
        return controller;
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }

    public JButton getBtnEditarPlaylist() {
        return btnEditarPlaylist;
    }

    public void setBtnEditarPlaylist(JButton btnEditarPlaylist) {
        this.btnEditarPlaylist = btnEditarPlaylist;
    }

    public JLabel getTxtNomePlaylist1() {
        return txtNomePlaylist1;
    }

    public void setTxtNomePlaylist1(JLabel txtNomePlaylist1) {
        this.txtNomePlaylist1 = txtNomePlaylist1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarPlaylist;
    private javax.swing.JLabel txtNomePlaylist1;
    // End of variables declaration//GEN-END:variables
}
